name: Production Deployment

on:
  push:
    branches: [main]

env:
  NODE_VERSION: '20'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy to Hostinger
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USER }}
          password: ${{ secrets.HOSTINGER_SSH_PASSWORD }}
          port: 22
          source: "./"
          target: /var/www/thequantics
          overwrite: true
          rm: true

      - name: Deploy as root
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          username: root # Using root directly
          password: ${{ secrets.HOSTINGER_SSH_PASSWORD }}
          port: 22
          script: |
            cd /var/www/thequantics
            
            # Install all dependencies as root
            npm install
            cd server && npm install --production && cd ..
            
            # PM2 setup as root
            npm install -g pm2
            pm2 delete thequanticsapp || true
            pm2 start /var/www/thequantics/ecosystem.config.cjs --env production
            pm2 save
            pm2 startup systemd -u root --hp /root